version: "3.8"
services:
  crawler:
    build: .
    image: crawler:latest
    container_name: metadata_${PREFIX:-1}
    networks:
      - meta
    environment:
      - PREFIX=${PREFIX:-1}
      - API_URL=http://api.proxy.ip2world.com/getProxyIp?num=1&lb=4&return_type=txt&protocol=http
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - DB_NAME=metadata
    volumes:
      - ./../docker_images/data:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - meta
    volumes:
      - ./../database:/data/db
      - ./data:/result
    #command: mongosh  --eval "use ${DB_NAME:-metadata};"
    restart: unless-stopped
networks:
  meta:
    driver: bridge
